name: GitHub Action Start
on: [push]
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is automatically triggered job by ${{ github.event_name }}"
      - run: echo "Operating system is ${{ runner.os }}"
      - run: echo "URL is ${{ vars.URL }}"