name: GitHub Action Start
on: [push]
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is automatically triggered job by ${{ github.event_name }}"
      - run: echo "Operating system is ${{ runner.os }}"
      - run: echo "URL is ${{ vars.URL }}"
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "The repo ${{ github.repository }} has been cloned"
      - name: "List files in repository"
        run: |
          ls -l ${{ github.workspace }}
      - run: echo "Job status is ${{ job.status }}"