name: Label Pull Requests
on: [pull_request]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Label pull Requests
        uses: actions/github-script@v7
        with:
          script: |
            const pull_number = context.issue.number;

            github.rest.isses.addLabels({
              issue_number: pull_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['requires_review']
            });